/* See repository update: Supabase email/password authentication, legacy auth bridge, authorized-user context, password recovery, and removal of Google/Microsoft login UI. */
(function(window) {
  "use strict";
  const config = window.APP_CONFIG || {};
  let supabaseInstance = null;
  const LEGACY_TOKEN_KEY = "SGT360_AUTH_TOKEN_V1";
  const LEGACY_SESSION_KEY = "SGT360_AUTH_SESSION_V1";
  function initSupabase() {
    const url = config.SUPABASE_URL || window.localStorage.getItem("S360_SUPABASE_URL");
    const key = config.SUPABASE_ANON_KEY || window.localStorage.getItem("S360_SUPABASE_ANON_KEY");
    if (url && key && window.supabase) {
      try {
        supabaseInstance = window.supabase.createClient(url, key, { auth: { persistSession: true, autoRefreshToken: true, detectSessionInUrl: true } });
        console.info("[SGT360] Supabase conectado:", url);
      } catch (err) { supabaseInstance = null; console.error("[SGT360] Error al inicializar Supabase:", err); }
    } else console.error("[SGT360] Supabase no está configurado.");
  }
  initSupabase();
  function getClient() { if (!supabaseInstance) initSupabase(); if (!supabaseInstance) throw new Error("No se pudo conectar con Supabase."); return supabaseInstance; }
  async function getAuthUser() { const { data, error } = await getClient().auth.getUser(); if (error) throw error; if (!data || !data.user) throw new Error("NO_AUTH_SESSION"); return data.user; }
  async function getAuthorizedUser() {
    const user = await getAuthUser();
    const email = String(user.email || "").trim().toLowerCase();
    if (!email) throw new Error("La cuenta de Supabase no tiene correo electrónico.");
    const { data, error } = await getClient().from("seg_usuarios").select("id_usuario, correo, nombre, telefono, rol, id_proveedor, id_oficina, id_grupo, estado, tipo_documento, numero_documento").ilike("correo", email).eq("estado", "ACTIVO").maybeSingle();
    if (error) throw error;
    if (!data) { await getClient().auth.signOut(); throw new Error("USUARIO_NO_AUTORIZADO: tu correo no está registrado como usuario activo en Seguimiento 360."); }
    return { authUser: user, usuario: data };
  }
  function syncLegacySessionSync() {
    try {
      if (String(window.localStorage.getItem(LEGACY_TOKEN_KEY) || "").trim()) return;
      for (let i = 0; i < window.localStorage.length; i++) {
        const key = window.localStorage.key(i) || "";
        if (!/^sb-.+-auth-token$/i.test(key)) continue;
        const raw = window.localStorage.getItem(key); if (!raw) continue;
        const parsed = JSON.parse(raw); const accessToken = parsed && (parsed.access_token || (parsed.currentSession && parsed.currentSession.access_token));
        if (accessToken) { window.localStorage.setItem(LEGACY_TOKEN_KEY, accessToken); window.localStorage.setItem(LEGACY_SESSION_KEY, raw); return; }
      }
    } catch (_) { window.localStorage.removeItem(LEGACY_TOKEN_KEY); window.localStorage.removeItem(LEGACY_SESSION_KEY); }
  }
  async function syncLegacySession() { try { const { data } = await getClient().auth.getSession(); const session = data && data.session; if (session && session.access_token) { window.localStorage.setItem(LEGACY_TOKEN_KEY, session.access_token); window.localStorage.setItem(LEGACY_SESSION_KEY, JSON.stringify({ user: session.user, expires_at: session.expires_at || null })); } } catch (_) {} }
  function showMessage(message, isError) { const el = document.getElementById("authMessage"); if (!el) return; el.hidden = false; el.textContent = message || ""; el.classList.toggle("is-error", !!isError); el.classList.toggle("is-success", !isError); }
  function normalizeAuthError(error) {
    const message = String(error && (error.message || error.error_description) || error || "");
    if (/invalid login credentials/i.test(message)) return "Correo o contraseña incorrectos.";
    if (/email not confirmed/i.test(message)) return "Debes confirmar tu correo antes de iniciar sesión.";
    if (/rate limit|too many requests/i.test(message)) return "Demasiados intentos. Espera unos minutos y vuelve a intentarlo.";
    if (/failed to fetch|network/i.test(message)) return "No se pudo conectar con Supabase. Verifica tu conexión.";
    return message || "No fue posible iniciar sesión.";
  }
  function installLoginView() {
    const authActions = document.querySelector(".auth-actions"); if (!authActions) return;
    /* const style = document.createElement("style"); style.id = "supabase-auth-styles";
    style.textContent = ".supabase-auth-form{display:grid;gap:12px;margin-top:4px}.supabase-auth-label{display:grid;gap:6px;font-size:12px;font-weight:700;color:#475569;text-align:left}.supabase-auth-input{width:100%;box-sizing:border-box;border:1px solid #cbd5e1;border-radius:12px;padding:12px 14px;font:inherit;background:#fff;color:#0f172a;outline:none}.supabase-auth-input:focus{border-color:#00a1de;box-shadow:0 0 0 3px rgba(0,161,222,.12)}.supabase-auth-submit{width:100%;justify-content:center;border:0;cursor:pointer}.supabase-auth-submit[disabled]{opacity:.65;cursor:wait}.supabase-auth-forgot{border:0;background:none;color:#007da9;font:inherit;font-size:13px;font-weight:700;cursor:pointer;padding:4px}.supabase-auth-forgot:hover{text-decoration:underline}#authMessage.is-success{color:#16794b}#authMessage.is-error{color:#b42318}";
    document.head.appendChild(style);
    authActions.innerHTML = '<form id="supabaseEmailLogin" class="supabase-auth-form" novalidate><label class="supabase-auth-label">Correo electrónico<input id="authEmail" class="supabase-auth-input" type="email" autocomplete="username" inputmode="email" placeholder="nombre@empresa.com" required></label><label class="supabase-auth-label">Contraseña<input id="authPassword" class="supabase-auth-input" type="password" autocomplete="current-password" placeholder="Ingresa tu contraseña" required minlength="6"></label><button id="authEmailSubmit" class="provider-button supabase-auth-submit" type="submit"><span class="material-symbols-rounded" aria-hidden="true">login</span><span>Iniciar sesión</span></button><button id="authForgotPassword" class="supabase-auth-forgot" type="button">¿Olvidaste tu contraseña?</button></form>';
    authActions.insertAdjacentHTML("beforeend", '<button id="supabaseGoogleButton" class="provider-button supabase-auth-submit" type="button">Continuar con Google</button><button id="supabaseMicrosoftButton" class="provider-button supabase-auth-submit" type="button">Continuar con Microsoft</button>'); */
    const form = document.getElementById("supabaseEmailLogin"); const emailInput = document.getElementById("authEmail"); const passwordInput = document.getElementById("authPassword"); const submit = document.getElementById("authEmailSubmit"); const forgot = document.getElementById("authForgotPassword");
    form.hidden = true;
    const emailButton = document.getElementById("supabaseEmailButton");
    emailButton.addEventListener("click", function() {
      form.hidden = !form.hidden;
      emailButton.setAttribute("aria-expanded", String(!form.hidden));
      if (!form.hidden) emailInput.focus();
    });
    form.addEventListener("submit", async function(event) {
      event.preventDefault(); const email = String(emailInput.value || "").trim().toLowerCase(); const password = String(passwordInput.value || "");
      if (!email || !emailInput.checkValidity()) return showMessage("Ingresa un correo válido.", true); if (!password) return showMessage("Ingresa tu contraseña.", true);
      submit.disabled = true; showMessage("Validando acceso…", false);
      try { const { data, error } = await getClient().auth.signInWithPassword({ email, password }); if (error) throw error; if (!data || !data.session) throw new Error("No se recibió una sesión válida de Supabase."); const auth = await getAuthorizedUser(); window.localStorage.setItem(LEGACY_TOKEN_KEY, data.session.access_token); window.localStorage.setItem(LEGACY_SESSION_KEY, JSON.stringify({ user: auth.authUser })); showMessage("Acceso autorizado. Cargando Seguimiento 360…", false); window.location.reload(); }
      catch (error) { try { await getClient().auth.signOut(); } catch (_) {} showMessage(normalizeAuthError(error), true); submit.disabled = false; passwordInput.focus(); }
    });
    forgot.addEventListener("click", async function() {
      const email = String(emailInput.value || "").trim().toLowerCase(); if (!email || !emailInput.checkValidity()) { showMessage("Ingresa primero tu correo para enviarte el enlace de recuperación.", true); emailInput.focus(); return; }
      forgot.disabled = true; try { const { error } = await getClient().auth.resetPasswordForEmail(email, { redirectTo: window.location.origin + window.location.pathname }); if (error) throw error; showMessage("Si el correo está registrado, recibirás un enlace para restablecer la contraseña.", false); } catch (error) { showMessage(normalizeAuthError(error), true); } finally { forgot.disabled = false; }
    });
    [
      { id: "supabaseGoogleButton", provider: "google" },
      { id: "supabaseMicrosoftButton", provider: "azure" }
    ].forEach(function(item) {
      const oauthButton = document.getElementById(item.id);
      if (!oauthButton) return;
      oauthButton.addEventListener("click", async function() {
        oauthButton.disabled = true;
        showMessage("Redirigiendo al proveedor de identidad...", false);
        try {
          const { error } = await getClient().auth.signInWithOAuth({
            provider: item.provider,
            options: {
              redirectTo: window.location.origin + window.location.pathname,
              scopes: item.provider === "azure" ? "email" : undefined
            }
          });
          if (error) throw error;
        } catch (error) {
          showMessage(normalizeAuthError(error), true);
          oauthButton.disabled = false;
        }
      });
    });
  }
  async function loadContext() {
    const authorized = await getAuthorizedUser(); const usuario = authorized.usuario; const role = String(usuario.rol || "USUARIO").toUpperCase(); const client = getClient();
    const context = { correcto: true, sesion: { idUsuario: usuario.id_usuario, correo: usuario.correo, nombre: usuario.nombre, rol: role, estado: usuario.estado, idProveedor: usuario.id_proveedor || "", idOficina: usuario.id_oficina || "", idGrupo: usuario.id_grupo || "" }, usuario: { idUsuario: usuario.id_usuario, correo: usuario.correo, nombre: usuario.nombre, rol: role, nombreRol: role, estado: usuario.estado, idProveedor: usuario.id_proveedor || "", idOficina: usuario.id_oficina || "", idGrupo: usuario.id_grupo || "" }, aplicacion: { nombre: config.APP_NAME || "Seguimiento 360", version: config.VERSION || "2.5.0", entorno: config.ENTORNO || "PRODUCCION", fechaServidor: new Date().toISOString() }, interfaz: { colorPrincipal: "#00A1DE", actualizacionAutomatica: true, actualizacionSegundos: 300 }, modulos: [], modulosPermitidos: [], permisos: {} };
    const { data: modules, error: modulesError } = await client.from("app_modulos").select("id_modulo,codigo,nombre,descripcion,icono,grupo_menu,orden,tipo_vista,estado").eq("estado", "ACTIVO").order("orden", { ascending: true }); if (modulesError) throw modulesError;
    const { data: rolePermissions, error: permissionError } = await client.from("seg_permisos").select("tipo_sujeto,id_sujeto,modulo,recurso,permitido,alcance,estado").eq("estado", "ACTIVO").in("id_sujeto", [role, usuario.id_usuario]); if (permissionError) throw permissionError;
    const allModules = role === "SUPERADMIN";
    // Para SUPERADMIN la consola ADMIN_CONFIG_APP concentra Usuarios, Roles,
    // Permisos y Estructura. Los módulos individuales continúan disponibles
    // para los demás roles, pero no se repiten en su menú.
    const integratedAdminModules = ["ADMIN_USUARIOS", "ADMIN_PERMISOS", "ADMIN_ESTRUCTURA"];
    const permitted = (modules || []).filter(function(module) { return (allModules || (rolePermissions || []).some(function(permission) { return permission.modulo === module.codigo && permission.permitido === true; })) && !(role === "SUPERADMIN" && integratedAdminModules.indexOf(module.codigo) !== -1); }).map(function(module) { return { idModulo: module.id_modulo, codigo: module.codigo, nombre: module.nombre, descripcion: module.descripcion, icono: module.icono || "grid_view", grupoMenu: module.grupo_menu || "General", orden: module.orden, tipoVista: module.tipo_vista }; });
    context.modulos = permitted; context.modulosPermitidos = permitted;
    const superadminResources = ["VISUALIZAR_MODULO","ADMINISTRAR","CREAR","EDITAR","ELIMINAR","IMPORTAR","EXPORTAR","VER_LISTADO","VER_DETALLE","EDITAR_PERMISOS","VER_MATERIALES","CREAR_MATERIAL","EDITAR_MATERIAL","GESTIONAR_CATALOGO","GESTIONAR_PRECIOS","CREAR_PRECIO_INDIVIDUAL","CREAR_LISTA_OFICIAL","EDITAR_LISTA_OFICIAL","REGISTRAR_VENTA","EDITAR_VENTA","CONFIRMAR_ABONO","PROGRAMAR_ENTREGA","CONFIRMAR_ENTREGA","ANULAR_VENTA","VER_PRECIOS","VER_LISTAS_OFICIALES","VER_MIS_LISTAS_PRECIO","VER_SOLICITUDES_PRECIO","CARGAR_LISTA_PRECIO","CARGAR_LISTA_PRECIO_ADMIN"];
    (modules || []).filter(function(module) { return module.estado === "ACTIVO"; }).forEach(function(module) { context.permisos[module.codigo] = context.permisos[module.codigo] || {}; if (role === "SUPERADMIN") superadminResources.forEach(function(resource) { context.permisos[module.codigo][resource] = { permitido: true, alcance: "TOTAL" }; }); });
    (rolePermissions || []).forEach(function(permission) { context.permisos[permission.modulo] = context.permisos[permission.modulo] || {}; context.permisos[permission.modulo][permission.recurso] = { permitido: permission.permitido === true, alcance: permission.alcance || "PROPIO" }; });
    context.seguridad = { permisos: context.permisos };
    // Mantiene una sesión técnica visible para la consola de Auditoría.
    // No impide el ingreso si la tabla aún no está disponible.
    try { const sessionId="SES-"+authorized.authUser.id; await client.from("seg_sesiones").upsert({id_sesion:sessionId,id_usuario:usuario.id_usuario,correo:usuario.correo,rol:role,fecha_inicio:new Date().toISOString(),ultima_actividad:new Date().toISOString(),estado:"ACTIVA",modulo_actual:window.APP_STATE&&window.APP_STATE.module||"INICIO",origen:"SUPABASE_AUTH"}); if(!window.sessionStorage.getItem("S360_AUDIT_LOGIN")){await client.from("seg_auditoria_accesos").insert({id_usuario:usuario.id_usuario,correo:usuario.correo,rol:role,modulo:"SISTEMA",accion:"INICIO_SESION",resultado:"AUTORIZADO",origen:"SUPABASE_AUTH",id_sesion:sessionId,detalle:{mensaje:"Sesión autenticada en Seguimiento 360"}});window.sessionStorage.setItem("S360_AUDIT_LOGIN","1");} } catch(_) {}
    return context;
  }
  function createGoogleScriptCompatibility() {
    const run = new Proxy({}, { get: function(_target, property) { if (property === "withSuccessHandler") return function(success) { let failure = null; const chain = new Proxy({}, { get: function(_chainTarget, method) { if (method === "withFailureHandler") return function(fail) { failure = fail; return chain; }; return function() { Promise.resolve(dispatchLegacyMethod(method)).then(function(result) { if (typeof success === "function") success(result); }).catch(function(error) { if (typeof failure === "function") failure(error); }); return chain; }; }}); return chain; }; return function() { return run; }; }});
    window.google = window.google || {}; window.google.script = window.google.script || {}; window.google.script.run = run;
  }
  async function dispatchLegacyMethod(method) {
    switch (String(method)) {
      case "validarSesionAplicacionPaso13D1": { const authorized = await getAuthorizedUser(); const session = (await getClient().auth.getSession()).data.session; return { correcto: true, autenticado: true, paso: "SUPABASE_AUTH", proveedorIdentidad: "SUPABASE_EMAIL", usuario: { idUsuario: authorized.usuario.id_usuario, correo: authorized.usuario.correo, nombre: authorized.usuario.nombre, rol: authorized.usuario.rol, idProveedor: authorized.usuario.id_proveedor || "" }, sesion: { fechaInicio: session && session.user && session.user.created_at ? session.user.created_at : "", ultimaActividad: new Date().toISOString(), fechaExpiracion: session && session.expires_at ? new Date(session.expires_at * 1000).toISOString() : "", estado: "ABIERTA", origen: "SUPABASE_EMAIL" }, configuracion: { segundosHeartbeat: 120, horasMaximas: 8 }, mensaje: "Sesión Supabase validada correctamente." }; }
      case "actualizarActividadSesionPaso13D1": await getAuthorizedUser(); return { correcto: true, autenticado: true, ultimaActividad: new Date().toISOString(), estado: "ABIERTA" };
      case "cerrarSesionAplicacionPaso13E1": await getClient().auth.signOut(); window.localStorage.removeItem(LEGACY_TOKEN_KEY); window.localStorage.removeItem(LEGACY_SESSION_KEY); return { correcto: true, mensaje: "Sesión cerrada." };
      case "obtenerConfiguracionPantallaLoginPaso13B": return { correcto: true, proveedores: { google: { habilitado: false }, microsoft: { habilitado: false } }, oauth: { preparado: false, inicioOAuthHabilitado: false } };
      default: throw new Error("Operación heredada no disponible con Supabase Auth: " + method);
    }
  }
  function installAdapterBridge() {
    if (!window.apiAdapter || window.apiAdapter.__s360SupabaseBridge) return;
    const originalExecuteRpc = window.apiAdapter.executeRpc.bind(window.apiAdapter);
    window.apiAdapter.executeRpc = async function(operation, argumentsList, moduleCode) {
      const authorized = await getAuthorizedUser();
      if (operation === "obtenerContextoAplicacion") return loadContext();
      const client = getClient();
      const direct = await executeSupabaseOperation(client, operation, argumentsList || [], authorized.usuario);
      if (direct !== undefined) return direct;
      const result = await originalExecuteRpc(operation, argumentsList, moduleCode);
      return normalizeModuleResponse(operation, result);
    };
    window.apiAdapter.__s360SupabaseBridge = true;
  }
  function normalizeModuleResponse(operation, result) {
    result = result || {};
    if (operation === "listarProveedoresModulo") return result.registros ? result : { registros: result.proveedores || [], paginacion: { pagina: 1, totalPaginas: 1 }, resumen: { total: (result.proveedores || []).length, activos: (result.proveedores || []).filter(function(x) { return x.estado === "ACTIVO"; }).length } };
    if (operation === "listarMaterialesPrecioModulo") return result.registros ? result : { registros: result.materiales || [], paginacion: { pagina: 1, totalPaginas: 1 } };
    if (operation === "listarVentasContadoModulo") return result.registros ? result : { registros: result.ventas || [], paginacion: { pagina: 1, totalPaginas: 1 } };
    return result;
  }
  async function executeSupabaseOperation(client, operation, args, user) {
    const query = async function(table, columns) { const response = await client.from(table).select(columns || "*"); if (response.error) throw response.error; return response.data || []; };
    const csv = function(headers, rows) { const cell = function(value) { const text = String(value == null ? "" : value); return '"' + text.replace(/"/g, '""') + '"'; }; return "\\ufeff" + [headers].concat(rows || []).map(function(row) { return row.map(cell).join(","); }).join("\\r\\n"); };
    const file = function(name, headers, rows) { return { nombre: name, nombreArchivo: name, contenido: csv(headers, rows), mimeType: "text/csv;charset=utf-8", cantidad: (rows || []).length }; };
    if (operation === "listarModulosAdminMotor") { const rows = await query("app_modulos"); return rows.map(function(x) { return { idModulo:x.id_modulo,codigo:x.codigo,nombre:x.nombre,descripcion:x.descripcion,icono:x.icono,grupoMenu:x.grupo_menu,orden:x.orden,tipoVista:x.tipo_vista,estado:x.estado }; }); }
    if (operation === "listarParametrosAdminMotor") { const rows = await query("sys_parametros"); return rows.map(function(x) { return { clave:x.clave,valor:x.valor,descripcion:x.descripcion,tipo:x.tipo,editable:x.editable !== false,estado:x.estado }; }); }
    if (operation === "listarCatalogosAdminMotor") { const rows = await query("app_catalogos"); const commercial=[{codigo:"MP_NEGOCIOS",nombre:"Negocios comerciales",descripcion:"Negocios disponibles para registrar ventas."},{codigo:"MP_MARCAS",nombre:"Marcas de materiales",descripcion:"Marcas disponibles en el maestro de materiales."}]; return rows.map(function(x) { return { idCatalogo:x.id_catalogo,codigo:x.codigo,nombre:x.nombre,descripcion:x.descripcion,estado:x.estado }; }).concat(commercial.filter(function(required){return !rows.some(function(x){return x.codigo===required.codigo;});}).map(function(required){return {idCatalogo:"SYSTEM-"+required.codigo,codigo:required.codigo,nombre:required.nombre,descripcion:required.descripcion,estado:"ACTIVO"};})); }
    if (operation === "listarRecursosVisualesAdminMotor") return [];
    if (operation === "listarRolesAdminMotor" || operation === "listarRolesAsignablesUsuariosMotor") { const rows = await query("seg_roles"); return { roles: rows.map(function(x) { return { idRol:x.id_rol,codigo:x.codigo,nombre:x.nombre,descripcion:x.descripcion,nivel:x.nivel,estado:x.estado,sistema:x.sistema }; }) }; }
    if (operation === "listarUsuariosAdminMotor") { const rows = await query("seg_usuarios"); return { registros: rows.map(function(x) { return { idUsuario:x.id_usuario, correo:x.correo, nombre:x.nombre, telefono:x.telefono, rol:x.rol, idProveedor:x.id_proveedor, idOficina:x.id_oficina, idGrupo:x.id_grupo, estado:x.estado, tipoDocumento:x.tipo_documento, numeroDocumento:x.numero_documento }; }), contextoAcceso: { idUsuario:user.id_usuario, rol:user.rol, alcance:"GLOBAL" } }; }
    if (operation === "listarSesionesAuditoriaAdminMotor") { const rows=await query("seg_sesiones");const users=await query("seg_usuarios");const filter=args[0]||{};const wanted=String(filter.estado||"ACTIVAS").toUpperCase();const records=rows.filter(function(x){return wanted==="TODOS" || (wanted==="ACTIVAS"?x.estado==="ACTIVA":x.estado===wanted);}).filter(function(x){const text=String(filter.texto||"").toLowerCase();return !text || [x.correo,x.rol,x.modulo_actual].join(" ").toLowerCase().indexOf(text)!==-1;}).map(function(x){const u=users.find(function(item){return item.id_usuario===x.id_usuario;})||{};return {idSesion:x.id_sesion,nombre:u.nombre||"",correo:x.correo,nombreRol:x.rol,proveedorIdentidad:x.origen||"SUPABASE",fechaInicio:x.fecha_inicio,ultimaActividad:x.ultima_actividad,fechaExpiracion:x.fecha_fin||"—",estado:x.estado,estadoOperativo:x.estado==="ACTIVA"?"VIGENTE":x.estado,moduloActual:x.modulo_actual||"—",puedeCerrar:x.estado==="ACTIVA",minutosDesdeActividad:Math.max(0,Math.round((Date.now()-new Date(x.ultima_actividad).getTime())/60000))};});return {registros:records,total:records.length,resumen:{activas:records.filter(function(x){return x.estado==="ACTIVA";}).length}}; }
    if (operation === "listarAuditoriaAdminMotor") { const all=await Promise.all([query("seg_auditoria_accesos"),query("seg_auditoria_eventos"),query("seg_auditoria_permisos")]);const filter=args[0]||{};const records=[].concat(all[0].map(function(x){return {fecha:x.fecha_hora,tipo:"ACCESOS",correo:x.correo,modulo:x.modulo,accion:x.accion,resultado:x.resultado,detalle:x.motivo||""};}),all[1].map(function(x){return {fecha:x.fecha_hora,tipo:"EVENTOS",correo:x.correo,modulo:x.modulo,accion:x.accion,resultado:x.resultado,detalle:x.entidad||x.id_entidad||""};}),all[2].map(function(x){return {fecha:x.fecha_hora,tipo:"PERMISOS",correo:x.correo,modulo:x.modulo,accion:x.recurso,resultado:"ACTUALIZADO",detalle:x.rol_objetivo||""};})).filter(function(x){const type=String(filter.tipo||"TODOS").toUpperCase(),text=String(filter.texto||"").toLowerCase();return (type==="TODOS"||x.tipo===type)&&(!text||Object.values(x).join(" ").toLowerCase().indexOf(text)!==-1);}).sort(function(a,b){return new Date(b.fecha)-new Date(a.fecha);});return {registros:records,total:records.length}; }
    if (operation === "guardarUsuarioAdminMotor") { const x=args[0] || {}; if(!x.idUsuario){const invited=await client.functions.invoke("invite-user",{body:{usuario:x,redirectTo:window.location.origin+window.location.pathname}});if(invited.error){let detail="";try{detail=await invited.error.context.json();}catch(_){ }throw new Error(detail&&detail.error || "No se encontró la función segura de invitaciones en Supabase. Despliega invite-user desde Edge Functions antes de crear usuarios.");}if(!invited.data || invited.data.correcto===false)throw new Error(invited.data && invited.data.error || "No fue posible enviar la invitación.");return invited.data;} const saved=await client.from("seg_usuarios").update({correo:String(x.correo || "").trim().toLowerCase(),nombre:x.nombre,telefono:x.telefono || null,rol:x.rol,id_proveedor:x.idProveedor || null,id_oficina:x.idOficina || null,id_grupo:x.idGrupo || null,estado:x.estado || "ACTIVO",tipo_documento:x.tipoDocumento || null,numero_documento:x.numeroDocumento || null,id_usuario_actualizacion:user.id_usuario}).eq("id_usuario",x.idUsuario); if(saved.error) throw saved.error; return {correcto:true,idUsuario:x.idUsuario}; }
    if (operation === "listarValoresCatalogoAdminMotor") { const code=String(args[0]||"").toUpperCase(); if(code==="MP_NEGOCIOS"){const rows=await query("mae_negocios");return rows.map(function(x){return {idValor:x.id_negocio,codigo:x.codigo_negocio,nombre:x.nombre,descripcion:x.descripcion,orden:1,estado:x.estado};});} if(code==="MP_MARCAS"){const rows=await query("mae_marcas");return rows.map(function(x){return {idValor:x.id_marca,codigo:x.codigo_marca,nombre:x.nombre,descripcion:x.descripcion,orden:1,estado:x.estado};});} const rows=await client.from("app_catalogo_valores").select("*").eq("catalogo",code).order("orden");if(rows.error)throw rows.error;return (rows.data||[]).map(function(x){return {idValor:x.id_valor,codigo:x.codigo,nombre:x.nombre,orden:x.orden,estado:x.estado};}); }
    if (operation === "guardarValorCatalogoAdminMotor") { const code=String(args[0]||"").toUpperCase();const x=args[1]||{};if(code==="MP_NEGOCIOS"){const id=x.idValor||"NEG-"+Date.now();const saved=await client.from("mae_negocios").upsert({id_negocio:id,codigo_negocio:x.codigo,nombre:x.nombre,descripcion:x.descripcion||null,estado:x.estado||"ACTIVO",id_usuario_actualizacion:user.id_usuario});if(saved.error)throw saved.error;return {correcto:true,idValor:id};}if(code==="MP_MARCAS"){const id=x.idValor||"MAR-"+Date.now();const saved=await client.from("mae_marcas").upsert({id_marca:id,codigo_marca:x.codigo,nombre:x.nombre,descripcion:x.descripcion||null,estado:x.estado||"ACTIVO",id_usuario_actualizacion:user.id_usuario});if(saved.error)throw saved.error;return {correcto:true,idValor:id};}const id=x.idValor||"CAT-"+Date.now();const saved=await client.from("app_catalogo_valores").upsert({id_valor:id,catalogo:code,codigo:x.codigo,nombre:x.nombre,orden:Number(x.orden||1),estado:x.estado||"ACTIVO"});if(saved.error)throw saved.error;return {correcto:true,idValor:id}; }
    if (operation === "obtenerEstructuraAsignacionesAdminMotor" || operation === "obtenerEstructuraAsignacionesUsuariosMotor") { const all = await Promise.all([query("mae_proveedores"),query("mae_oficinas"),query("mae_grupos"),query("rel_proveedor_oficinas"),query("seg_usuarios")]); const offices=all[1].map(function(x){return {idOficina:x.id_oficina,nombre:x.nombre,descripcion:x.descripcion,estado:x.estado};}); const groups=all[2].map(function(x){const office=offices.find(function(o){return o.idOficina===x.id_oficina;});return {idGrupo:x.id_grupo,idOficina:x.id_oficina,nombre:x.nombre,nombreOficina:office&&office.nombre,descripcion:x.descripcion,estado:x.estado};}); return { proveedores:all[0].map(function(x){const ids=String(x.codigo_canales_venta||"").split("|").filter(Boolean);return {idProveedor:x.id_proveedor,razonSocial:x.razon_social,nombreComercial:x.nombre_comercial,descripcion:x.descripcion,idsOficina:ids,oficinas:offices.filter(function(o){return ids.indexOf(o.idOficina)!==-1;}),alcanceCatalogo:x.alcance_catalogo,estado:x.estado};}), oficinas:offices, grupos:groups, relacionesProveedorOficina:all[3].map(function(x){return {idRelacion:x.id_relacion,idProveedor:x.id_proveedor,idOficina:x.id_oficina,idsGrupo:String(x.ids_grupo||"").split("|").filter(Boolean),estado:x.estado};}), tiposDocumento:Array.from(new Set(all[4].map(function(x){return x.tipo_documento;}).filter(Boolean))).map(function(code){return {codigo:code,nombre:code};}), reglas:{} }; }
    if (operation === "obtenerMatrizPermisosAdminMotor") { const role = String(args[0] || ""); const allModules = await query("app_modulos"); const rows = await query("seg_permisos"); const resources = ["VISUALIZAR_MODULO","CREAR","EDITAR","IMPORTAR","EXPORTAR","VER_LISTADO","CREAR_MATERIAL","EDITAR_MATERIAL","REGISTRAR_VENTA","CONFIRMAR_ABONO","PROGRAMAR_ENTREGA","GESTIONAR_PRECIOS"]; return { alcancesDisponibles:["PROPIO","PROVEEDOR","GRUPO","ASIGNADOS","GLOBAL"], modulos:allModules.filter(function(x){return x.estado === "ACTIVO";}).map(function(module){return {codigo:module.codigo,recursos:resources.map(function(code,index){const saved=rows.find(function(x){return x.id_sujeto === role && x.modulo === module.codigo && x.recurso === code && x.estado === "ACTIVO";});return {codigo:code,nombre:code.replace(/_/g," "),tipo:"ACCIÓN",orden:index,permitido:!!(saved && saved.permitido),alcance:(saved && saved.alcance)||"PROPIO"};})};}) }; }
    if (operation === "guardarMatrizPermisosAdminMotor") { const payload=args[0] || {}; const changes=payload.permisos || []; for (let i=0;i<changes.length;i+=1) { const x=changes[i]; const row={id_permiso:"PERM-"+payload.rol+"-"+x.modulo+"-"+x.recurso,tipo_sujeto:"ROL",id_sujeto:payload.rol,modulo:x.modulo,recurso:x.recurso,permitido:!!x.permitido,alcance:x.alcance || "PROPIO",estado:"ACTIVO"}; const saved=await client.from("seg_permisos").upsert(row); if(saved.error) throw saved.error; } return executeSupabaseOperation(client,"obtenerMatrizPermisosAdminMotor",[payload.rol],user); }
    if (operation === "obtenerOpcionesProveedorModulo") { const all=await Promise.all([query("mae_oficinas"),query("mae_grupos")]); return { oficinas:all[0].filter(function(x){return x.estado === "ACTIVO";}).map(function(x){return {idOficina:x.id_oficina,nombre:x.nombre,descripcion:x.descripcion};}), grupos:all[1].filter(function(x){return x.estado === "ACTIVO";}).map(function(x){return {idGrupo:x.id_grupo,idOficina:x.id_oficina,nombre:x.nombre};}) }; }
    if (operation === "obtenerPlantillaProveedoresModulo") return file("plantilla_proveedores.csv",["RAZON_SOCIAL","NOMBRE_COMERCIAL","CODIGO_SAP","RUC","DESCRIPCION","CODIGO_CANALES_VENTA","CODIGO_GRUPOS_VENDEDORES"],[]);
    if (operation === "guardarProveedorModulo" || operation === "guardarProveedorAdminMotor") { const x=args[0] || {}; const id=x.idProveedor || "PRV-"+Date.now(); const idsOficina=Array.isArray(x.idsOficina)?x.idsOficina:[]; const idsGrupo=Array.isArray(x.idsGrupo)?x.idsGrupo:[]; const saved=await client.from("mae_proveedores").upsert({id_proveedor:id,razon_social:x.razonSocial || x.nombreComercial || "Proveedor",nombre_comercial:x.nombreComercial || x.razonSocial || "Proveedor",nombre:x.nombreComercial || x.razonSocial || "Proveedor",codigo_sap:x.codigoSap || null,ruc:x.ruc || null,descripcion:x.descripcion || null,alcance_catalogo:x.alcanceCatalogo || "TOTAL",codigo_canales_venta:idsOficina.join("|"),codigo_grupos_vendedores:idsGrupo.join("|"),estado:x.estado || "ACTIVO",id_usuario_actualizacion:user.id_usuario}); if(saved.error) throw saved.error; const old=await client.from("rel_proveedor_oficinas").delete().eq("id_proveedor",id); if(old.error) throw old.error; const allGroups=await query("mae_grupos"); for(let i=0;i<idsOficina.length;i+=1){const groups=idsGrupo.filter(function(groupId){return allGroups.some(function(group){return group.id_grupo===groupId && group.id_oficina===idsOficina[i];});});const relation=await client.from("rel_proveedor_oficinas").insert({id_relacion:"RPO-"+id+"-"+idsOficina[i],id_proveedor:id,id_oficina:idsOficina[i],ids_grupo:groups.join("|"),alcance_grupos:groups.length?"SELECCIONADOS":"TODOS",estado:"ACTIVO",id_usuario_actualizacion:user.id_usuario});if(relation.error)throw relation.error;} return {correcto:true,idProveedor:id,nombreComercial:x.nombreComercial || x.razonSocial}; }
    if (operation === "guardarOficinaAdminMotor") { const x=args[0]||{}; if(!String(x.idOficina||"").trim()) throw new Error("El ID de oficina es obligatorio."); const saved=await client.from("mae_oficinas").upsert({id_oficina:x.idOficina,nombre:x.nombre,descripcion:x.descripcion||null,estado:x.estado||"ACTIVO",id_usuario_actualizacion:user.id_usuario});if(saved.error)throw saved.error;return {correcto:true,idOficina:x.idOficina}; }
    if (operation === "guardarGrupoAdminMotor") { const x=args[0]||{}; if(!String(x.idGrupo||"").trim() || !String(x.idOficina||"").trim()) throw new Error("El ID del grupo y la oficina son obligatorios."); const saved=await client.from("mae_grupos").upsert({id_grupo:x.idGrupo,id_oficina:x.idOficina,nombre:x.nombre,descripcion:x.descripcion||null,estado:x.estado||"ACTIVO",id_usuario_actualizacion:user.id_usuario});if(saved.error)throw saved.error;return {correcto:true,idGrupo:x.idGrupo}; }
    if (operation === "guardarMaterialPrecioModulo") { const x=args[0] || {}; const id=x.idMaterial || "MAT-"+Date.now(); let brandId=String(x.idMarca || "").trim(); if(brandId){const brands=await query("mae_marcas");const found=brands.find(function(b){return b.id_marca===brandId || String(b.nombre).toLowerCase()===brandId.toLowerCase();});if(found)brandId=found.id_marca;else{brandId="MAR-"+Date.now();const brand=await client.from("mae_marcas").insert({id_marca:brandId,codigo_marca:brandId,nombre:String(x.idMarca).trim(),estado:"ACTIVO",id_usuario_actualizacion:user.id_usuario});if(brand.error)throw brand.error;}} const saved=await client.from("mae_materiales").upsert({id_material:id,codigo_material:x.codigoMaterial || id,codigo_sap:x.codigoSap || null,id_producto:x.idProducto || null,id_tipo_material:x.idTipoMaterial || null,id_subtipo_material:x.idSubtipoMaterial || null,id_marca:brandId || null,nombre_material:x.nombreMaterial || x.descripcionMaterial || "Material",descripcion_material:x.descripcionMaterial || null,unidad_medida:x.unidadMedida || "UND",es_gasodomestico:!!x.esGasodomestico,estado:x.estado || "ACTIVO",id_usuario_actualizacion:user.id_usuario}); if(saved.error) throw saved.error; return {correcto:true,idMaterial:id,mensaje:"Material guardado correctamente."}; }
    if (operation === "listarProveedoresModulo") { const rows = await query("mae_proveedores"); const records = rows.map(function(x) { return { idProveedor:x.id_proveedor,razonSocial:x.razon_social,nombreComercial:x.nombre_comercial,codigoSap:x.codigo_sap,ruc:x.ruc,descripcion:x.descripcion,idsOficina:String(x.codigo_canales_venta||"").split("|").filter(Boolean),idsGrupo:String(x.codigo_grupos_vendedores||"").split("|").filter(Boolean),alcanceCatalogo:x.alcance_catalogo,estado:x.estado }; }); return normalizeModuleResponse(operation, { proveedores: records }); }
    if (operation === "listarMaterialesPrecioModulo" || operation === "listarMaterialesSelectPreciosModulo") { const all=await Promise.all([query("mae_materiales"),query("mae_marcas")]); const records = all[0].map(function(x) { const brand=all[1].find(function(b){return b.id_marca===x.id_marca;}); return { idMaterial:x.id_material,codigoMaterial:x.codigo_material,codigoSap:x.codigo_sap,idMarca:x.id_marca,marca:brand&&brand.nombre,nombreMaterial:x.nombre_material,descripcionMaterial:x.descripcion_material,unidadMedida:x.unidad_medida,estado:x.estado }; }); return operation === "listarMaterialesSelectPreciosModulo" ? { registros: records } : normalizeModuleResponse(operation, { materiales: records }); }
    if (operation === "obtenerOpcionesMaterialesPreciosModulo") { const all=await Promise.all([query("mae_proveedores"),query("mae_oficinas"),query("mae_grupos"),query("mae_materiales"),query("mae_marcas"),query("mae_negocios"),query("mae_productos_principales"),query("mae_tipos_material"),query("mae_subtipos_material"),query("sys_parametros")]);const activeCode=String((all[9].find(function(x){return x.clave==="NEGOCIO_VENTAS_ACTIVO";})||{}).valor||"").trim();const businesses=all[5].filter(function(x){return x.estado==="ACTIVO" && (!activeCode || x.codigo_negocio===activeCode);}); return { negocios:businesses.map(function(x){return {id:x.id_negocio,nombre:x.nombre};}), productos:all[6].filter(function(x){return businesses.some(function(b){return b.id_negocio===x.id_negocio;});}).map(function(x){return {id:x.id_producto,idNegocio:x.id_negocio,nombre:x.nombre};}), tipos:all[7].map(function(x){return {id:x.id_tipo_material,nombre:x.nombre,clavePadre:"MP_PRODUCTOS_PRINCIPALES",valorPadre:"PROD-GSD"};}), subtipos:all[8].map(function(x){return {id:x.id_subtipo_material,idProducto:x.id_producto,idTipoMaterial:x.id_tipo_material,nombre:x.nombre,clavePadre:"MP_TIPOS_MATERIAL",valorPadre:x.id_tipo_material,metadata:{productoPrincipal:x.id_producto}};}), marcas:all[4].map(function(x){return {id:x.id_marca,nombre:x.nombre};}), unidades:[{id:"UND",nombre:"Unidad"}], proveedores:all[0].map(function(x){return {idProveedor:x.id_proveedor,nombre:x.nombre_comercial || x.razon_social};}), oficinas:all[1].map(function(x){return {idOficina:x.id_oficina,nombre:x.nombre};}), grupos:all[2].map(function(x){return {idGrupo:x.id_grupo,idOficina:x.id_oficina,nombre:x.nombre};}), materiales:all[3].map(function(x){return {idMaterial:x.id_material,codigoMaterial:x.codigo_material,nombreMaterial:x.nombre_material};}) }; }
    if (operation === "obtenerPlantillaMaterialesModulo") return file("plantilla_materiales.csv",["CODIGO_SAP","NOMBRE_MATERIAL","DESCRIPCION_MATERIAL","MARCA","UNIDAD_MEDIDA","ESTADO"],[]);
    if (operation === "obtenerPlantillaPreciosIndividualesModulo" || operation === "obtenerPlantillaListaPreciosModulo") return file("plantilla_precios.csv",["CODIGO_SAP","CODIGO_MATERIAL","PRECIO_BASE","MONEDA","FECHA_INICIO","FECHA_FIN","DETALLE_COMBO"],[]);
    if (operation === "listarListasOficialesPreciosModulo") { const all=await Promise.all([query("pre_lista_precio_detalle"),query("pre_listas_precios"),query("mae_materiales"),query("mae_proveedores"),query("mae_negocios")]); const rows=all[0].map(function(d){const list=all[1].find(function(x){return x.id_lista_precio===d.id_lista_precio;})||{};const material=all[2].find(function(x){return x.id_material===d.id_material;})||{};const provider=all[3].find(function(x){return x.id_proveedor===list.id_proveedor;})||{};const business=all[4].find(function(x){return x.id_negocio===list.id_negocio;})||{};return {idDetallePrecio:d.id_detalle_precio,idListaPrecio:d.id_lista_precio,proveedor:provider.nombre_comercial||provider.razon_social||"—",negocio:business.nombre||"—",idProveedor:list.id_proveedor,idNegocio:list.id_negocio,idOficina:list.id_oficina,idGrupo:list.id_grupo,codigoSap:material.codigo_sap,codigoMaterial:material.codigo_material,idMaterial:material.id_material,nombreCortoMaterial:material.nombre_material,descripcionMaterial:material.descripcion_material,precioBase:d.precio_base,moneda:d.moneda||list.moneda,fechaInicio:list.fecha_inicio,fechaFin:list.fecha_fin,detalleCombo:d.detalle_combo,estado:d.estado};}); return {registros:rows,paginacion:{pagina:1,totalPaginas:1,total:rows.length}}; }
    if (operation === "guardarPrecioIndividualMaterialesPreciosModulo") { const x=args[0]||{}; let listId=x.idListaPrecio||"LPR-"+Date.now(); if(!x.idListaPrecio){const list=await client.from("pre_listas_precios").insert({id_lista_precio:listId,codigo_lista:listId,nombre:"Lista "+listId,id_proveedor:x.idProveedor,id_negocio:x.idNegocio||null,id_oficina:x.idOficina||null,id_grupo:x.idGrupo||null,fecha_inicio:x.fechaInicio,fecha_fin:x.fechaFin||null,moneda:x.moneda||"PEN",estado:"ACTIVA",id_usuario_actualizacion:user.id_usuario});if(list.error)throw list.error;} const detailId=x.idDetallePrecio||"DPR-"+Date.now();const detail=await client.from("pre_lista_precio_detalle").upsert({id_detalle_precio:detailId,codigo_precio:detailId,id_lista_precio:listId,id_material:x.idMaterial,precio_base:Number(x.precioBase),moneda:x.moneda||"PEN",tiene_combo:String(x.tieneCombo||"").toUpperCase()==="SI",detalle_combo:x.detalleCombo||null,descripcion_combo:x.detalleCombo||null,estado:"ACTIVO",id_usuario_actualizacion:user.id_usuario});if(detail.error)throw detail.error;return {correcto:true,mensaje:"El precio fue registrado.",precioVista:{idDetallePrecio:detailId,idListaPrecio:listId,idProveedor:x.idProveedor,idNegocio:x.idNegocio,idOficina:x.idOficina,idGrupo:x.idGrupo,idMaterial:x.idMaterial,precioBase:x.precioBase,moneda:x.moneda||"PEN",fechaInicio:x.fechaInicio,fechaFin:x.fechaFin,detalleCombo:x.detalleCombo||"",proveedor:x._labelProveedor,negocio:x._labelNegocio}}; }
    if (operation === "exportarMaterialesModulo") { const rows=await query("mae_materiales"); return file("materiales.csv",["CODIGO_MATERIAL","CODIGO_SAP","NOMBRE","DESCRIPCION","UNIDAD","ESTADO"],rows.map(function(x){return [x.codigo_material,x.codigo_sap,x.nombre_material,x.descripcion_material,x.unidad_medida,x.estado];})); }
    if (operation === "exportarPreciosOficialesModulo") { const result=await executeSupabaseOperation(client,"listarListasOficialesPreciosModulo",args,user); return file("precios.csv",["PROVEEDOR","NEGOCIO","CODIGO_MATERIAL","MATERIAL","PRECIO","MONEDA","INICIO","FIN"],result.registros.map(function(x){return [x.proveedor,x.negocio,x.codigoMaterial,x.nombreCortoMaterial,x.precioBase,x.moneda,x.fechaInicio,x.fechaFin];})); }
    if (operation === "exportarProveedoresModulo") { const rows=await query("mae_proveedores"); return file("proveedores.csv",["ID_PROVEEDOR","RAZON_SOCIAL","NOMBRE_COMERCIAL","CODIGO_SAP","RUC","CANALES","GRUPOS","ESTADO"],rows.map(function(x){return [x.id_proveedor,x.razon_social,x.nombre_comercial,x.codigo_sap,x.ruc,x.codigo_canales_venta,x.codigo_grupos_vendedores,x.estado];})); }
    if (operation === "confirmarAbonoVentaContadoModulo" || operation === "observarAbonoVentaContadoModulo") { const x=args[0]||{}; const id=String(x.idVenta||"").trim(); if(!id) throw new Error("No se indicó la venta a validar."); const approved=operation==="confirmarAbonoVentaContadoModulo"; if(!approved && !String(x.observacion||x.observacionConfirmacionAbono||"").trim()) throw new Error("La observación del abono es obligatoria."); const changes={estado_abono:approved?"ABONO_CONFIRMADO":"ABONO_OBSERVADO",estado_entrega:approved?"POR_ENTREGAR":"REGISTRADA",id_usuario_actualizacion:user.id_usuario}; if(x.observacion||x.observacionConfirmacionAbono) changes.observaciones=String(x.observacion||x.observacionConfirmacionAbono); const saved=await client.from("vta_ventas_contado").update(changes).eq("id_venta",id).select("estado_abono,estado_entrega").single(); if(saved.error) throw saved.error; return {correcto:true,estadoAbono:saved.data.estado_abono,estado:saved.data.estado_entrega,mensaje:approved?"Abono aprobado.":"Abono observado."}; }
    if (operation === "obtenerContextoVentasContadoModulo") { const context = await loadContext(); const p = context.permisos.VENTAS_CONTADO || {}; const all=await Promise.all([query("mae_negocios"),query("mae_oficinas"),query("mae_grupos"),query("sys_parametros")]);const businessCode=String((all[3].find(function(x){return x.clave==="NEGOCIO_VENTAS_ACTIVO";})||{}).valor||"").trim();const offices=all[1].filter(function(x){return x.estado==="ACTIVO";}).map(function(x){return {idOficina:x.id_oficina,nombre:x.nombre};});const groupsByOffice={};all[2].filter(function(x){return x.estado==="ACTIVO";}).forEach(function(x){(groupsByOffice[x.id_oficina]=groupsByOffice[x.id_oficina]||[]).push({idGrupo:x.id_grupo,nombre:x.nombre});}); return { permisos:{ puedeListar:!!(p.VISUALIZAR_MODULO && p.VISUALIZAR_MODULO.permitido), puedeRegistrar:!!(p.REGISTRAR_VENTA && p.REGISTRAR_VENTA.permitido), puedeEditar:!!(p.EDITAR_VENTA && p.EDITAR_VENTA.permitido), puedeValidarAbono:!!(p.CONFIRMAR_ABONO && p.CONFIRMAR_ABONO.permitido), puedeGestionarEntrega:!!(p.PROGRAMAR_ENTREGA && p.PROGRAMAR_ENTREGA.permitido), puedeExportar:!!(p.EXPORTAR && p.EXPORTAR.permitido) }, vistaInicial:"REGISTRADAS", estados:[], estadosAbono:[], negociosVenta:all[0].filter(function(x){return x.estado==="ACTIVO" && (!businessCode || x.codigo_negocio===businessCode);}).map(function(x){return {codigo:x.id_negocio,nombre:x.nombre};}), comercial:{oficinas:offices,gruposPorOficina:groupsByOffice,idOficinaPredeterminada:user.id_oficina||"",idGrupoPredeterminado:user.id_grupo||""} }; }
    return undefined;
  }
  function installAuthBridge() {
    installLoginView(); createGoogleScriptCompatibility(); installAdapterBridge(); syncLegacySessionSync(); syncLegacySession();
    const client = getClient(); client.auth.onAuthStateChange(function(_event, session) { if (session && session.access_token) window.localStorage.setItem(LEGACY_TOKEN_KEY, session.access_token); else { window.localStorage.removeItem(LEGACY_TOKEN_KEY); window.localStorage.removeItem(LEGACY_SESSION_KEY); } });
  }
  window.supabaseClient = { getClient: getClient, isConfigured: function() { return !!supabaseInstance; }, getAuthUser: getAuthUser, getAuthorizedUser: getAuthorizedUser, reconfigure: function(url, key) { window.localStorage.setItem("S360_SUPABASE_URL", url); window.localStorage.setItem("S360_SUPABASE_ANON_KEY", key); config.SUPABASE_URL = url; config.SUPABASE_ANON_KEY = key; initSupabase(); return !!supabaseInstance; }, clearConfig: function() { window.localStorage.removeItem("S360_SUPABASE_URL"); window.localStorage.removeItem("S360_SUPABASE_ANON_KEY"); config.SUPABASE_URL = ""; config.SUPABASE_ANON_KEY = ""; supabaseInstance = null; }, subirArchivoEvidencia: async function(archivo, nombreRuta) { const client = getClient(); await getAuthorizedUser(); const bucket = config.STORAGE_BUCKETS && config.STORAGE_BUCKETS.EVIDENCIAS || "evidencias"; const path = nombreRuta || `entrega_${Date.now()}_${archivo.name}`; const { data, error } = await client.storage.from(bucket).upload(path, archivo, { cacheControl: "3600", upsert: true }); if (error) throw new Error("Error al subir archivo a Supabase Storage: " + error.message); const { data: publicUrlData } = client.storage.from(bucket).getPublicUrl(path); return { correcto: true, urlPublica: publicUrlData.publicUrl, idArchivo: data.path }; } };
  document.addEventListener("DOMContentLoaded", function() { try { installAuthBridge(); } catch (error) { console.error("[SGT360] No fue posible instalar el puente Supabase:", error); showMessage("No fue posible preparar la autenticación. Revisa la configuración de Supabase.", true); } }, { once: true });
})(window);
